name: s6-tablero
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile    
    hostname: frontend.tablero-contrataciones.pdn
    restart: always
    ports:
      - ${FRONT_PORT}:80
